version: '3.3'

services:
  sdi-database:
    container_name: sdi-database
    build:
      context: database
    networks:
      - resilient-sdi-network

  user-database:
    image: postgres:9.6
    environment: :
      - POSTGRES_DB=user-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes:
      - /Users/helissonnas/data/users_db:/var/lib/postgresql/data/

  sdi-gateway:
    container_name: sdi-gateway
    networks:
      - resilient-sdi-network
    build:
      context: sdi-gateway
    ports:
      - '8080:8080'
    depends_on:
      - feature-retriever

  feature-retriever:
    container_name: feature-retriever
    environment:
      - DB_URL=jdbc:postgresql://sdi-database:5432/inde_database_docker
      - PORT=8080
    networks:
      - resilient-sdi-network
    build:
      context: feature-retriever
    depends_on:
      - sdi-database

  service-finder:
    container_name: service-finder
    environment:
      - DB_URL=jdbc:postgresql://sdi-database:5432/inde_database_docker
      - PORT=8080
    networks:
      - resilient-sdi-network
    build:
      context: service-finder

  users-service:
    container_name: users-service
    environment:
      - DB_URL=jdbc:postgresql://user-database:5432/user-database
      - PORT=8080
    networks:
      - resilient-sdi-network
    build:
      context: users-service

networks:
  resilient-sdi-network:
