spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/user_db}
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: ${PORT:8089}