spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/user-database}
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: ${PORT:8089}
