dictionary = {"a.a.": "ao ano",
              "AEB": "Agência Espacial Brasileira",
              "AFD": "Assentamento Funcional Digital",
              "AGU": "Advocacia-Geral da União",
              "ANA": "Agência Nacional de Águas",
              "ANAC": "Agência Nacional de Aviação Civil",
              "Anatel": "Agência Nacional de Telecomunicações",
              "Ancine": "Agência Nacional do Cinema",
              "Aneel": "Agência Nacional de Energia Elétrica",
              "ANP": "Agência Nacional de Petróleo, Gás Natural e Combustíveis Renováveis",
              "Antaq": "Agência Nacional de Transportes Aquaviários",
              "APS": "Agência da Previdência Social",
              "Assec/MP": "Assessoria Econômica do Ministério do Planejamento",
              "Ater": "Assistência Técnica e Extensão Rural",
              "Bacen": "Banco Central do Brasil",
              "Basa": "Banco da Amazônia",
              "BB": "Banco do Brasil",
              "BNB": "Banco do Nordeste",
              "BNDES": "Banco Nacional de Desenvolvimento Econômico e Social",
              "BPC": "Benefício de Prestação Continuada",
              "Bric": "Brasil, Rússia, Índia e China",
              "BRTs": "Sistemas de Ônibus Rápidos",
              "Caged": "Cadastro Geral de Empregados e Desempregados",
              "Capes": "Coordenação de Aperfeiçoamento de Pessoal de Nível Superior",
              "Caricom": "Comunidade do Caribe",
              "CBERS": "Programa Sino-Brasileiro de Satélites de Recursos Terrestres",
              "CCC": "Conta de Consumo de Combustíveis Fósseis",
              "CCOPAB": "Centro Conjunto de Operações de Paz no Brasil",
              "CCPs": "Centros Comunitários de Produção",
              "CDB": "Convenção sobre Diversidade Biológica",
              "CDFMM": "Conselho Diretor do Fundo da Marinha Mercante",
              "CDI": "Conselhos de Direito do Idoso",
              "CEF": "Caixa Econômica Federal",
              "CedocPrev": "Centros de Documentação Previdenciária",
              "Ceitec": "Centro Nacional de Tecnologia Eletrônica Avançada",
              "CEO": "Centros de Especialidade Odontológica",
              "CGASS": "Comitê Gestor de Atenção à Saúde do Servidor",
              "CISSP": "Comissão interna de Saúde do Servidor por Local de Trabalho",
              "Cide": "Combustíveis - Contribuição de Intervenção no Domínio Econômico",
              "CNARH": "Cadastro Nacional de Usuários de Recursos Hídricos",
              "CNDS": "Compromisso Nacional pelo Desenvolvimento Social",
              "CNEM": "Comissão Nacional de Energia Nuclear",
              "CMN": "Conselho Monetário Nacional",
              "CNIS": "Cadastro Nacional de Informações Sociais",
              "CNJ": "Conselho Nacional de Justiça",
              "CNPq": "Conselho Nacional de Desenvolvimento Científico e Tecnológico",
              "Codefat": "Conselho Deliberativo do Fundo de Amparo ao Trabalhador",
              "Cons": "Contribuição para o Financiamento da Seguridade Social",
              "Copom": "Comitê de Política Monetária do Banco Central",
              "Cras": "Centros de Referência da Assistência Social",
              "Creas": "Centros de Referência Especializados de Assistência Social",
              "Crema": "Programa de Contrato de Restauração e Manutenção",
              "C,T&I": "Ciência Tecnologia e Inovação",
              "CTPS": "Carteira de Trabalho e Previdência Social",
              "CVT": "Centros Vocacionais Tecnológicos",
              "DCTA": "Departamento de Ciência e Tecnologia Aeroespacial",
              "Denatran": "Departamento Nacional de Trânsito",
              "Depen": "Departamento Penitenciário Nacional",
              "DLSP": "Dívida Líquida do Setor Público",
              "DPF": "Dívida Pública Federal",
              "DPFe": "Dívida Pública Federal externa",
              "DPMFi": "Dívida Pública Mobiliária Federal interna",
              "DST": "Doenças Sexualmente Transmissíveis",
              "EACF": "Estação Antártica Comandante Ferraz",
              "EC": "Emenda Constitucional",
              "EDN": "Estratégia Nacional de Defesa",
              "EJA": "Educação de Jovens e Adultos",
              "Embrapa": "Empresa Brasileira de Pesquisa Agropecuária",
              "Embraer": "Empresa Brasileira de Aeronáutica",
              "Emgea": "Empresa Gestora de Ativos",
              "Encomex": "Encontros de Comércio Exterior",
              "END": "Estratégia Nacional de Defesa",
              "ESB": "Equipe de Saúde Bucal",
              "FAB": "Força Aérea Brasileira",
              "FAR": "Fundo de Arrendamento Residencial",
              "FAT": "Fundo de Amparo ao Trabalhador",
              "FCO": "Fundo Constitucional de Financiamento do Centro-Oeste",
              "FDS": "Fundo de Desenvolvimento Social",
              "FED": "Federal Reserve",
              "FGTS": "Fundo de Garantia por Tempo de Serviço",
              "Fies": "Fundo de Financiamento ao Estudante do Ensino Superior",
              "Fifa": "Fédération Internationale de Football Association",
              "Finep": "Financiadora de Estudos e Projetos",
              "Finame": "Agência Especial de Financiamento Industrial",
              "FMM": "Fundo da Marinha Mercante",
              "FNC": "Fundo Nacional da Cultura",
              "FNE": "Fundo Constitucional de Financiamento do Nordeste",
              "FNHIS": "Fundo de Habitação de Interesse Social",
              "FNO": "Fundo Constitucional de Financiamento do Norte",
              "FNSP": "Fundo Nacional de Segurança Pública",
              "FPM": "Fundo de Participação dos Municípios",
              "FSA": "Fundo Setorial do Audiovisual",
              "Funai": "Fundação Nacional do Índio",
              "Funasa": "Fundação Nacional de Saúde",
              "Funarte": "Fundação Nacional de Artes",
              "Fundeb": "Fundo de Manutenção e Desenvolvimento da Educação Básica e de Valorização dos Profissionais da Educação",
              "Funpen": "Fundo Penitenciário Nacional",
              "Funttel": "Fundo para o Desenvolvimento Tecnológico das Telecomunicações",
              "Gesac": "Governo Eletrônico Serviço de Atendimento ao Cidadão",
              "GNL": "Gás Natural Liquefeito",
              "GPM-BR": "Satélite do Programa Internacional de Medidas de Precipitação",
              "Ibas": "Índia, Brasil e África do Sul",
              "Ideb": "Índice de Desenvolvimento da Educação Básica",
              "IDH": "Índice de Desenvolvimento Humano",
              "IED": "Investimentos Estrangeiros Diretos",
              "IFI": "Instituto de Fomento Industrial",
              "IGD": "Índice de Gestão Descentralizada",
              "IGP-DI": "Índice Geral de Preços – Disponibilidade Interna",
              "Infopen": "Sistema Integrado de Informações Penitenciárias",
              "INB": "Indústrias Nucleares do Brasil",
              "INCTs": "Institutos Nacionais de Ciência e Tecnologia",
              "Inep": "Instituto Nacional de Estudos e Pesquisas Educacionais",
              "Infraero": "Empresa Brasileira de Infraestrutura Aeroportuária",
              "INPC": "Índice Nacional de Preços ao Consumidor",
              "Inpe": "Instituto Nacional de Pesquisas Espaciais",
              "INPI": "Instituto Nacional da Propriedade Industrial",
              "INSS": "Instituto Nacional de Seguro Social",
              "IOF": "Imposto sobre Operações de Crédito, Câmbio e Seguros",
              "Ipea": "Instituto de Pesquisa Econômica Aplicada",
              "IPI": "Imposto sobre Produtos Industrializados",
              "ISI": "Institute for Scientific Information",
              "ITR": "Imposto sobre a Propriedade Territorial Rural",
              "Loas": "Lei Orgânica da Assistência Social",
              "LT": "Linha de Transmissão",
              "Mapa": "Ministério da Agricultura, Pecuária e Abastecimento",
              "Mapsar": "Satélite de Sensoriamento Remoto com Imageador Radar",
              "MB": "Marinha do Brasil",
              "MCidades": "Ministério das Cidades",
              "MCT": "Ministério da Ciência e Tecnologia",
              "MD": "Ministério da Defesa",
              "MDA": "Ministério do Desenvolvimento Agrário",
              "MDIC": "Ministério do Desenvolvimento, Indústria e Comércio Exterior",
              "MDL": "Mecanismo de Desenvolvimento Limpo",
              "ME": "Ministério do Esporte",
              "Mercosul": "Mercado Comum do Sul",
              "MF": "Ministério da Fazenda",
              "MinC": "Ministério da Cultura",
              "Minustah": "Missão das Nações Unidas para Estabilização do Haiti",
              "MJ": "Ministério da Justiça",
              "MMA": "Ministério do Meio Ambiente",
              "MME": "Ministério de Minas e Energia",
              "MP": "Ministério do Planejamento, Orçamento e Gestão",
              "MPA": "Ministério da Pesca e Aquicultura",
              "MPEs": "Micro e Pequenas Empresas Exportadoras",
              "MPF": "Ministério Público Federal",
              "MPS": "Ministérios da Previdência Social",
              "MPT": "Ministério Público do Trabalho",
              "MPU": "Ministério Público da União",
              "MRE": "Ministério das Relações Exteriores",
              "MS": "Ministério da Saúde",
              "MT": "Ministério dos Transportes",
              "MTE": "Ministério do Trabalho e Emprego",
              "MTur": "Ministério do Turismo",
              "MVA": "Mega Volt-Ampère",
              "NFSP": "Necessidade de Financiamento do Setor Público",
              "Obmep": "Olimpíada Brasileira de Matemática nas Escolas Públicas",
              "OIT": "Organização Internacional do Trabalho",
              "ONU": "Organização das Nações Unidas",
              "p.p.": "pontos percentuais",
              "PAA": "Programa de Aquisição de Alimentos",
              "PAC": "Programa de Aceleração do Crescimento",
              "PAC2": "Programa de Aceleração do Crescimento 2",
              "Pacti": "Plano de Ação em Ciência, Tecnologia e Inovação",
              "PAF": "Plano Anual de Financiamento",
              "PAR": "Plano de Ação Articulada",
              "PASS": "Política de Atenção à Saúde do Servidor",
              "PBF": "Programa Bolsa Família",
              "PCD": "Pessoa com Deficiência",
              "PCN": "Programa Calha Norte",
              "PDB": "Política de Desenvolvimento da Biotecnologia",
              "PDDE": "Programa Dinheiro Direto na Escola",
              "PDE": "Plano de Desenvolvimento da Educação",
              "PDEE": "Plano Decenal de Expansão de Energia",
              "PDG": "Programa de Dispêndios Globais",
              "P&D": "Pesquisa e Desenvolvimento",
              "PD&I": "Pesquisa, Desenvolvimento e Inovação",
              "PEA": "População Economicamente Ativa",
              "Pemaer": "Plano Estratégico Militar da Aeronáutica",
              "PET": "Programa de Educação Tutorial",
              "Peti": "Programa de Erradicação do Trabalho Infantil ",
              "Petrobras": "Petróleo Brasileiro",
              "PEX": "Plano de Expansão da Rede de Atendimento da Previdência Social",
              "PGPAF": "Programa de Garantia de Preços para a Agricultura Familiar",
              "PIB": "Produto Interno Bruto",
              "Planar": "Plano de Ações Articuladas",
              "PLDO": "Projeto de Lei de Diretrizes Orçamentárias",
              "PLO": "Projeto de Lei Orçamentária",
              "Ploa": "Projeto de Lei Orçamentária Anual",
              "PMCMV": "Programa Minha Casa, Minha Vida",
              "PME": "Pesquisa Mensal do Emprego",
              "CAR": "Cadastro Ambiental Rural",
              "PNAD": "Pesquisa Nacional por Amostra de Domicílios",
              "Pnae": "Programa Nacional de Alimentação Escolar",
              "PNAE": "Programa Nacional de Atividades Espaciais",
              "Pnaes": "Programa Nacional de Assistência Estudantil",
              "Pnate": "Programa de Apoio ao Transporte Escolar na Educação Básica",
              "PNBL": "Plano Nacional de Banda Larga",
              "PNCF": "Programa Nacional de Crédito Fundiário",
              "PND": "Programa Nacional de Dragagem",
              "PNDH": "Programa Nacional de Direitos Humanos",
              "PNDP": "Política Nacional de Desenvolvimento de Pessoal",
              "PNI": "Programa Nacional de Imunização",
              "PNLD": "Programa Nacional do Livro Didático",
              "PNLT": "Programa Nacional de Logística e Transportes",
              "PNMC": "Plano Nacional sobre Mudança do Clima",
              "PNPB": "Programa Nacional de Produção e Uso do Biodiesel",
              "PNQ": "Plano Nacional de Qualificação",
              "PNRA": "Plano Nacional de Reforma Agrária",
              "PNSP": "Plano Nacional de Segurança Pública",
              "PPCDAM": "Plano de Ação para Prevenção e Controle do Desmatamento na Amazônia Legal",
              "PPCerrado": "Plano de Ação para Prevenção e Controle do Desmatamento e de Queimadas no Cerrado",
              "PQSP": "Programa de Qualificação Social e Profissional",
              "Previc": "Superintendência Nacional de Previdência Complementar",
              "Proagro": "Programa de Garantia da Atividade Agropecuária",
              "Proantar": "Programa Antártico Brasileiro",
              "Prodetur": "Programa de Desenvolvimento do Turismo",
              "Proeja": "O Programa Nacional de Integração da Educação Profissional com a Educação Básica na Modalidade de Educação de Jovens e Adultos",
              "Proesf": "Programa de Expansão e Consolidação da Saúde da Família",
              "Proex": "Programa de Financiamento às Exportações",
              "Proext": "Programa de Extensão Universitária",
              "Profaa": "Programa de Auxílio a Aeroportos",
              "Proinfa": "Programa de Incentivo às Fontes Alternativas de Energia Elétrica",
              "Proinfra": "Programa de Apoio à Infraestrutura Institucional de Ciência e Tecnologia",
              "ProJovem": "Programa Nacional de Inclusão de Jovens",
              "Proger Rural": "Programa de Geração de Emprego e Renda Rural",
              "Programa ABC": "Programa Agricultura de Baixo Carbono",
              "Prominp": "Programa de Mobilização da Indústria Nacional de Petróleo e Gás Natural",
              "Pronaf": "Programa Nacional de Fortalecimento da Agricultura Familiar",
              "Pronamp": "Programa Nacional de Apoio ao Médio Produtor Rural",
              "Pronasci": "Programa Nacional de Segurança Pública com Cidadania",
              "PRO-REG": "Programa de Regulamentação do Governo Federal",
              "Prosub": "Programa de Desenvolvimento de Submarinos",
              "Protejo": "Proteção de Jovens em Território Vulnerável",
              "Psan": "Política de Segurança Alimentar e Nutricional",
              "PSB": "Proteção Social Básica",
              "PSI": "Plano de Sustentação de Investimento",
              "PSS": "Plano de Seguridade do Servidor Público",
              "Rais": "Relação Anual de Informações Sociais",
              "Rede Cicex": "Rede de Centros de Informação de Comércio Exterior",
              "Renadi": "Rede Nacional de Proteção e Defesa dos Direitos dos Idosos",
              "Reuni": "Programa de Apoio a Planos de Reestruturação e Expansão das Universidades Federais Brasileiras",
              "RFB": "Receita Federal do Brasil",
              "RGPS": "Regime Geral de Previdência Social",
              "Rides": "Regiões Integradas de Desenvolvimento",
              "RMV": "Renda Mensal Vitalícia",
              "RNP": "Rede Nacional de Ensino e Pesquisa",
              "RPPS": "Regime Próprio de Previdência Social",
              "Rute": "Rede Universitária de Telemedicina",
              "SASS": "Sistema de Atenção à Saúde do Servidor",
              "Samu": "Serviço de Atendimento Móvel de Urgência",
              "SBPE": "Sistema Brasileiro de Poupança e Empréstimo",
              "SBTVD": "Sistema Brasileiro de Televisão Digital",
              "Seaf": "Seguro da Agricultura Familiar",
              "SDH": "Secretaria dos Direitos Humanos",
              "SGB": "Satélite Geoestacionário Brasileiro",
              "Selic": "Taxa Referencial do Sistema Especial de Liquidação e Custódia",
              "Senasp": "Secretaria Nacional de Segurança Pública",
              "SEP": "Secretaria de Portos",
              "SEPPIR": "Secretaria Especial de Políticas de Promoção da Igualdade Racial",
              "Siape": "Sistema Integrado de Administração de Recursos Humanos",
              "Siass": "Subsistema Integrado de Atenção à Saúde do Servidor Público Federal",
              "Sibe": "Sistema Integrado de Benefícios",
              "Siga": "Sistema de Inteligência Gerencial de Auditoria",
              "SIN": "Sistema Interligado Nacional",
              "Sine": "Sistema Nacional de Emprego",
              "Sinesp": "Sistema Nacional de Estatísticas de Segurança Pública",
              "Sisceab": "Sistema de Controle do Espaço Aéreo Brasileiro",
              "Sisvant": "Sistema de Veículos Aéreos Não Tripulados",
              "SNCT": "Semana Nacional de Ciência e Tecnologia",
              "SNJ": "Secretaria Nacional de Juventude",
              "SNUC": "Sistema Nacional de Unidades de Conservação",
              "SOF/MP": "Secretaria de Orçamento Federal",
              "SPE/MF": "Secretaria de Política Econômica",
              "SPM": "Secretaria Especial de Políticas para as Mulheres",
              "SPSR": "Subvenção ao Prêmio do Seguro Rural",
              "SRH/MP": "Secretaria de Recursos Humanos do Ministério do Planejamento, Orçamento e Gestão",
              "STN": "Secretaria do Tesouro Nacional",
              "Suas": "Sistema Único de Assistência Social",
              "Suframa": "Superintendência da Zona Franca de Manaus",
              "SUS": "Sistema Único de Saúde",
              "Susp": "Sistema Único de Segurança Pública",
              "TAV": "Trem de Alta Velocidade",
              "TCJ": "Termo de Conciliação Judicial",
              "TCU": "Tribunal de Contas da União",
              "Telecentros BR": "Programa Nacional de Apoio à Inclusão Digital nas Comunidades",
              "TIN": "Telecentros de Informação e Negócios",
              "TICs": "Tecnologias de Informação e Comunicação",
              "TMI": "Torre Móvel de Integração",
              "TJLP": "Taxa de Juros de Longo Prazo",
              "UBS": "Unidade Básicas de Saúde",
              "CNAE": "Classificação Nacional de Atividades Econômicas",
              "CNAES": "Classificação Nacional de Atividades Econômicas",
              "SUPBAP": "Superintendência Regional Baixo Paraíba do Sul",
              "UC": "Unidade de Conservação",
              "UFPE": "Universidade Federal de Pernambuco",
              "UFRGS": "Universidade Federal do Rio Grande do Sul",
              "UHE": "Usinas Hidrelétricas",
              "Unasul": "União de Nações Sul-Americanas",
              "UP": "Unidade de Pesquisa",
              "UPA": "Unidade de Pronto Atendimento",
              "URV": "Unidade Real de Valor",
              "USA": "Unidade de Suporte Avançado",
              "USB": "Unidade de Suporte Básico",
              "UTE": "Usina Termelétrica",
              "VLS": "Veículo Lançador de Satélites",
              "MEI": "Microempreendedor Individual"
              }


def mach_acronym(acc):
    try:
        return dictionary[acc]
    except:
        return acc
