spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/inde_database_docker}
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: ${PORT:8088}

feign:
  client:
    config:
      api-search-engine:
        name: api-search-engine
        url: localhost:5000